structure(list(url = "https://koina.wilhelmlab.org/v2/models/not_a_valid_model_name/ready", 
    status_code = 400L, headers = structure(list(server = "nginx/1.24.0 (Ubuntu)", 
        date = "Thu, 29 Aug 2024 11:10:55 GMT", `content-type` = "text/plain", 
        `content-length` = "0", `x-powered-by` = "Express"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 400L, version = "HTTP/2", 
        headers = structure(list(server = "nginx/1.24.0 (Ubuntu)", 
            date = "Thu, 29 Aug 2024 11:10:55 GMT", `content-type` = "text/plain", 
            `content-length` = "0", `x-powered-by` = "Express"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(""), date = structure(1724929855, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 3e-05, 
    connect = 3e-05, pretransfer = 0.000142, starttransfer = 0.002907, 
    total = 0.002925)), class = "response")
